version: '3.9'

services:
  ticaret:
    image: ticaret:0.0.1
    ports:
      - 9094:8080
    environment:
      DB_URL: "jdbc:h2:tcp://h2db/ticaret-db;DB_CLOSE_DELAY=-1"
      DB_USERNAME: "demir"
      DB_PASSWORD: "demir"

  h2db:
    image: buildo/h2database
    ports:
      - 9092:8082